name: Build
on: 
  push:
    branch: master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps: 
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Remove .gitignore
        run: rm .gitignore
      - name: Install dependencies
        run: npm install
      - name: Install dev dependencies
        run: npm install -dev
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './out/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1